version: "3.9"

services:
  mongo:
    image: mongo:7
    container_name: drivebetter_mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: drivebetter
    volumes:
      - mongo_data:/data/db

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: drivebetter_app
    command: npm run dev
    environment:
      NODE_ENV: development
      PORT: 3000
      MONGODB_URI: mongodb://mongo:27017/drivebetter
      JWT_SECRET: dev_super_secret
      GOOGLE_CLIENT_ID: your-google-client-id.apps.googleusercontent.com
      GOOGLE_CLIENT_SECRET: your-google-client-secret
      GOOGLE_CALLBACK_URL: http://localhost:3000/api/v1/oauth/google/callback
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - mongo

volumes:
  mongo_data:
